#!/bin/bash

# Utility function to check for errors and exit if so
function check_exit {
    if (($?)); then
        echo "**** Pre-commit hook failed"
        exit 1
    fi
}

TOP=`git rev-parse --show-toplevel`
COOKBOOKS=$TOP/cookbooks

echo "---- Checking whitespace"
git diff-index --check --cached HEAD --
check_exit

echo "---- Checking for 'tailor' in PATH"
TAILOR=`which tailor`
if (($?)); then
    echo "---- Checking for 'tailor-2.5' in PATH"
    TAILOR=`which tailor-2.5`
    check_exit
fi

echo "---- Checking for clean tailor scan"
git diff-index --name-only --diff-filter=ACM HEAD -- '*.rb' | while read file; do
    $TAILOR -c "$TOP/.tailor" "$file"
    check_exit
done
check_exit

TEST=`git diff-index --name-only HEAD -- "*cookbooks/bcpc/*" | wc -l`
if (($TEST>0)); then
	echo "---- Checking knife cookbook tests"
	knife cookbook test bcpc -o "$COOKBOOKS"
	check_exit

	echo "---- Checking for 'foodcritic' in PATH"
	FOODCRITIC=`which foodcritic`
	check_exit

	echo "---- Checking for clean foodcritic scan"
	$FOODCRITIC -f any -t ~FC014 -t ~FC048 -t ~FC023 "$COOKBOOKS/bcpc"
	check_exit
fi
