#!/usr/bin/env python

"""Checks that apache is up and running on all interfaces it should be.

"""


if __name__ == '__main__':
   
   import yaml
   import sys
   import requests
   config = yaml.load(open(sys.argv[1], "r"))

   rc = { "result": "OKAY",
          "msg" : "" }
   if config.get("status_url"):
      try:
         r = requests.get(config["stats_url"])
         if r.status_code !=200:
            rc["result"] = "ERROR"
            rc["msg"] += "Status returned %d\n" % r.status_code
      except requests.exceptions.ConnectionError: 
            rc["result"] = "ERROR"
            rc["msg"] += "Unable to get stats\n"
      

   for ip in config["ips"]:
      try:
         r = requests.get(ip["ip"])
         if r.status_code !=200:
            rc["result"] = "ERROR"
            rc["msg"]  += "Status %s returned %d\n" % (ip["name"], r.status_code)
      except requests.exceptions.ConnectionError: 
         rc["result"] = "ERROR"
         rc["msg"]  += "%s: Unable to connect to  %s \n"(ip["name"], ip["ip"])
         
   print yaml.dump(rc)
   sys.exit(0)
   
