#!/usr/bin/env python

"""Checks that mysql is up and clustered correctly

"""


if __name__ == '__main__':
   
   import yaml
   import sys
   import requests
   config = yaml.load(open(sys.argv[1], "r"))

   rc = { "result": "OKAY",
          "msg" : "" }
   import MySQLdb as mdb
   try:
      con = mdb.connect('localhost', 'root', config["mysql_root_password"]);
   except:
      rc["result"] = "ERROR"
      rc["msg"] = "Unable to connect to local mysql"      
      print yaml.dump(rc)
      sys.exit(0)
 
   c = con.cursor()
   c.execute("show status like 'wsrep_ready';")
   k , v = c.fetchone()
   if v!= "ON":
      rc["result"] = "ERROR"
      rc["msg"] = "wsrep_ready is %s" %  v
   c.execute("show status like 'wsrep_incoming_addresses';")
   k, v = c.fetchone()
   ips = v.split(",")

   c.execute("show status like 'wsrep_cluster_size';")
   k, v = c.fetchone()
   if int(v) != len(ips):
      rc["result"] = "ERROR"
      rc["msg"] = "cluster size is %d but ips are %s" %(int(v), ",".join(ips))

   c.execute("show status like 'wsrep_local_state_comment';")
   k, v = c.fetchone()
   if v != "Synced":
      rc["result"] = "ERROR"
      rc["msg"] = "local state is %s"  % (v,)
      
   print yaml.dump(rc)   
   sys.exit(0)
   
